services:
  rdesktop:
    image: lscr.io/linuxserver/rdesktop:ubuntu-xfce
    container_name: rdesktop
    security_opt:
      - seccomp:unconfined #optional
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Aisa/ShangHai
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock #optional
      - /your/data/config:/config #optional
    ports:
      - 3389:3389
    shm_size: 3gb #optional
    restart: unless-stopped
networks: {}
